"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Background, Controls, MarkerType, ReactFlow, useReactFlow, type Edge, type Node } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { create } from "zustand";
import { toPng } from "html-to-image";
import { applyOps, compactDiagram, emptyDiagram, publicDiagramOpsSchema, type Diagram, type DiagramOp } from "@/lib/diagram";
import { layoutDiagram } from "@/lib/layout";
import { HandTracker, type HandDebug } from "@/components/hand-tracker";
import { WebSpeechTranscriptSource, type TranscriptHandlers, type TranscriptSource } from "@/lib/transcript-source";

type BoardStatus = "Idle" | "Listening" | "Thinking" | "Drawing";
type Session = { title?: unknown; subjectHint?: unknown; diagram: Diagram; opsLog: DiagramOp[][]; transcript: string };
type BoardStore = {
  diagram: Diagram; undoStack: Diagram[]; opsLog: DiagramOp[][]; transcript: string; interim: string; status: BoardStatus; pointedNodeIds: string[]; selectedNodeIds: string[];
  apply: (ops: DiagramOp[]) => Diagram; setPositions: (nodes: Diagram["nodes"]) => void; setPointed: (id: string | null) => void; toggleSelected: () => void; toggleSelectedNode: (id: string) => void;
  addFinal: (text: string) => void; setInterim: (text: string) => void; setStatus: (status: BoardStatus) => void; undo: () => void; restore: (session: Pick<Session, "diagram" | "opsLog" | "transcript">) => void; reset: () => void;
};
const useBoard = create<BoardStore>((set, get) => ({
  diagram: emptyDiagram(), undoStack: [], opsLog: [], transcript: "", interim: "", status: "Idle", pointedNodeIds: [], selectedNodeIds: [],
  apply: (ops) => { const next = applyOps(get().diagram, ops); set((state) => ({ undoStack: [...state.undoStack, structuredClone(state.diagram)], opsLog: [...state.opsLog, ops], diagram: next, status: "Drawing" })); return next; },
  setPositions: (nodes) => set((state) => ({ diagram: { ...state.diagram, nodes } })), setPointed: (id) => set({ pointedNodeIds: id ? [id] : [] }),
  toggleSelected: () => { const id = get().pointedNodeIds[0]; if (id) get().toggleSelectedNode(id); },
  toggleSelectedNode: (id) => set((state) => ({ pointedNodeIds: [id], selectedNodeIds: state.selectedNodeIds.includes(id) ? state.selectedNodeIds.filter((selected) => selected !== id) : [...state.selectedNodeIds, id].slice(-2) })),
  addFinal: (text) => set((state) => ({ transcript: `${state.transcript} ${text}`.trim(), interim: "" })), setInterim: (interim) => set({ interim }), setStatus: (status) => set({ status }),
  undo: () => set((state) => { const previous = state.undoStack.at(-1); return previous ? { diagram: previous, undoStack: state.undoStack.slice(0, -1), opsLog: state.opsLog.slice(0, -1), status: "Idle" } : state; }),
  restore: (session) => set({ diagram: session.diagram, undoStack: [], opsLog: session.opsLog, transcript: session.transcript, interim: "", status: "Idle", pointedNodeIds: [], selectedNodeIds: [] }),
  reset: () => set({ diagram: emptyDiagram(), undoStack: [], opsLog: [], transcript: "", interim: "", status: "Idle", pointedNodeIds: [], selectedNodeIds: [] }),
}));

const accent: Record<string, string> = { concept: "#e6a75b", actor: "#7ab8c4", process: "#b394d8", stage: "#77b78c", data: "#d7828b", example: "#d8b55e", note: "#c6c5bd" };
const WATER_CYCLE = ["The sun heats the ocean, causing evaporation.", "Water vapor rises and cools into clouds through condensation.", "Then precipitation falls from clouds back to the ocean, and the cycle repeats."];
const WORLD_WAR_I = ["World War One began in 1914 after the assassination of Archduke Franz Ferdinand.", "The alliance system drew Germany, Austria-Hungary, France, Britain, and Russia into the conflict.", "The war ended in 1918, followed by the Treaty of Versailles."];

function ViewportFitter({ signature, manualUntilRef }: { signature: string; manualUntilRef: React.RefObject<number> }) {
  const { fitView } = useReactFlow();
  useEffect(() => { if (Date.now() < manualUntilRef.current) return; const timer = window.setTimeout(() => void fitView({ padding: 0.22, duration: 500 }), 0); return () => window.clearTimeout(timer); }, [fitView, manualUntilRef, signature]);
  return null;
}

function GestureLayer({ areaRef, diagram, setPointed, toggleSelected, undo, setDebug }: { areaRef: React.RefObject<HTMLElement | null>; diagram: Diagram; setPointed: (id: string | null) => void; toggleSelected: () => void; undo: () => void; setDebug: (debug: HandDebug & { screen: { x: number; y: number }; flow: { x: number; y: number }; pointed: string | null }) => void }) {
  const { screenToFlowPosition, fitView } = useReactFlow(); const cursorRef = useRef<HTMLDivElement>(null); const hoverRef = useRef<{ id: string; since: number } | null>(null);
  useEffect(() => { const fit = () => void fitView({ padding: 0.22, duration: 300 }); window.addEventListener("chalk:fit-view", fit); return () => window.removeEventListener("chalk:fit-view", fit); }, [fitView]);
  const onPoint = useCallback((point: { x: number; y: number }) => { const bounds = areaRef.current?.getBoundingClientRect(); if (!bounds) return; const screen = { x: bounds.left + point.x * bounds.width, y: bounds.top + point.y * bounds.height }; const flow = screenToFlowPosition(screen); if (cursorRef.current) cursorRef.current.style.transform = `translate(${screen.x}px, ${screen.y}px)`; const node = diagram.nodes.find((candidate) => { const width = Math.max(130, candidate.label.length * 11 + 40); return flow.x >= candidate.x && flow.x <= candidate.x + width && flow.y >= candidate.y && flow.y <= candidate.y + 64; }); const id = node?.id ?? null; const current = hoverRef.current; if (!id) { hoverRef.current = null; setPointed(null); return; } if (!current || current.id !== id) { hoverRef.current = { id, since: performance.now() }; return; } if (performance.now() - current.since >= 400) setPointed(id); }, [areaRef, diagram.nodes, screenToFlowPosition, setPointed]);
  const onDebug = useCallback((debug: HandDebug) => { const bounds = areaRef.current?.getBoundingClientRect(); const screen = bounds ? { x: bounds.left + debug.point.x * bounds.width, y: bounds.top + debug.point.y * bounds.height } : { x: 0, y: 0 }; setDebug({ ...debug, screen, flow: screenToFlowPosition(screen), pointed: useBoard.getState().pointedNodeIds[0] ?? null }); }, [areaRef, screenToFlowPosition, setDebug]);
  return <><div ref={cursorRef} className="pointer-events-none fixed z-30 size-4 -translate-x-1/2 -translate-y-1/2 rounded-full border-2 border-[#e6a75b] bg-[#e6a75b]/30" /><HandTracker onPoint={onPoint} onPinch={toggleSelected} onSwipeLeft={undo} onError={() => undefined} onDebug={onDebug} /></>;
}

function isSession(value: unknown): value is Session { return Boolean(value && typeof value === "object" && "diagram" in value && "opsLog" in value && "transcript" in value && typeof (value as Session).transcript === "string" && Array.isArray((value as Session).opsLog)); }

export function ChalkBoard() {
  const { diagram, undoStack, opsLog, transcript, interim, status, pointedNodeIds, selectedNodeIds, apply, setPositions, setPointed, toggleSelected, addFinal, setInterim, setStatus, undo, restore, reset } = useBoard();
  const [text, setText] = useState(""); const [title, setTitle] = useState("Untitled lesson"); const [subjectHint, setSubjectHint] = useState("Water cycle"); const [error, setError] = useState(""); const [isListening, setIsListening] = useState(false); const [isExportingHandout, setIsExportingHandout] = useState(false); const [isReplay, setIsReplay] = useState(false); const [replayIndex, setReplayIndex] = useState(0); const [isPlaying, setIsPlaying] = useState(false); const [debugEnabled, setDebugEnabled] = useState(false);
  const [debug, setDebug] = useState<HandDebug & { screen: { x: number; y: number }; flow: { x: number; y: number }; pointed: string | null }>({ gesture: "Off", pinchDistance: 0, point: { x: 0, y: 0 }, fps: 0, screen: { x: 0, y: 0 }, flow: { x: 0, y: 0 }, pointed: null });
  const sourceRef = useRef<TranscriptSource | null>(null); const listeningRef = useRef(false); const requestRef = useRef<AbortController | null>(null); const queuedRef = useRef(""); const transcriptRef = useRef(""); const subjectRef = useRef(subjectHint); const scrollRef = useRef<HTMLDivElement>(null); const sendRef = useRef<() => void>(() => undefined); const canvasAreaRef = useRef<HTMLElement>(null); const fileInputRef = useRef<HTMLInputElement>(null); const manualViewportUntilRef = useRef(0);
  useEffect(() => { transcriptRef.current = transcript; }, [transcript]); useEffect(() => { subjectRef.current = subjectHint; }, [subjectHint]); useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight }); }, [transcript, interim]);
  const finishDrawing = useCallback(() => window.setTimeout(() => setStatus(listeningRef.current ? "Listening" : "Idle"), 450), [setStatus]);
  const send = useCallback(async () => { const delta = queuedRef.current.trim(); if (!delta || requestRef.current || isReplay) return; queuedRef.current = ""; const controller = new AbortController(); requestRef.current = controller; setStatus("Thinking"); try { const response = await fetch("/api/interpret", { method: "POST", signal: controller.signal, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcriptDelta: delta, recentTranscript: `${transcriptRef.current} ${delta}`.trim().slice(-1500), diagram: compactDiagram(useBoard.getState().diagram), pointerContext: { pointedNodeIds: useBoard.getState().pointedNodeIds, selectedNodeIds: useBoard.getState().selectedNodeIds }, subjectHint: subjectRef.current || undefined }) }); const parsed = publicDiagramOpsSchema.safeParse(await response.json()); if (!response.ok || !parsed.success) throw new Error("Chalk could not interpret that yet. Please try again."); const nextDiagram = apply(parsed.data.ops); setPositions(await layoutDiagram(nextDiagram)); finishDrawing(); } catch (caught) { if (!(caught instanceof DOMException && caught.name === "AbortError")) { setError(caught instanceof Error ? caught.message : "Try again."); setStatus(listeningRef.current ? "Listening" : "Idle"); } } finally { requestRef.current = null; if (queuedRef.current.trim() && !controller.signal.aborted) sendRef.current(); } }, [apply, finishDrawing, isReplay, setPositions, setStatus]);
  useEffect(() => { sendRef.current = () => void send(); }, [send]);
  const enqueueFinal = useCallback((value: string, sendImmediately: boolean) => { const clean = value.trim(); if (!clean || isReplay) return; addFinal(clean); queuedRef.current = `${queuedRef.current} ${clean}`.trim(); if (sendImmediately) void send(); }, [addFinal, isReplay, send]);
  useEffect(() => { const interval = window.setInterval(() => { if (queuedRef.current.trim().length >= 80 && !requestRef.current) void send(); }, 4000); return () => window.clearInterval(interval); }, [send]);
  const stopListening = useCallback(() => { listeningRef.current = false; setIsListening(false); sourceRef.current?.stop(); sourceRef.current = null; queuedRef.current = ""; requestRef.current?.abort(); requestRef.current = null; setInterim(""); setStatus("Idle"); }, [setInterim, setStatus]);
  const startListening = useCallback(() => { setError(""); const source = new WebSpeechTranscriptSource(); if (!source.supported) { setError("Speech recognition needs Chrome desktop. Typed input is ready below."); return; } sourceRef.current = source; listeningRef.current = true; setIsListening(true); setStatus("Listening"); const handlers: TranscriptHandlers = { onFinal: (finalText) => enqueueFinal(finalText, true), onInterim: setInterim, onError: (message) => { setError(message); stopListening(); }, onEnd: () => { if (listeningRef.current) window.setTimeout(() => { if (listeningRef.current) source.start(handlers); }, 150); } }; source.start(handlers); }, [enqueueFinal, setInterim, setStatus, stopListening]);
  useEffect(() => () => stopListening(), [stopListening]); useEffect(() => { const onKeyDown = (event: KeyboardEvent) => { if ((event.ctrlKey || event.metaKey) && event.key.toLowerCase() === "z") { event.preventDefault(); undo(); } }; window.addEventListener("keydown", onKeyDown); return () => window.removeEventListener("keydown", onKeyDown); }, [undo]);
  const submitTyped = useCallback(() => { enqueueFinal(text, true); setText(""); }, [enqueueFinal, text]);
  const downloadBlob = (name: string, blob: Blob) => { const link = document.createElement("a"); const url = URL.createObjectURL(blob); link.href = url; link.download = name; link.click(); window.setTimeout(() => URL.revokeObjectURL(url), 0); };
  const download = (name: string, content: string, type: string) => downloadBlob(name, new Blob([content], { type }));
  const downloadDataUrl = async (name: string, dataUrl: string) => downloadBlob(name, await (await fetch(dataUrl)).blob());
  const exportJson = () => download("chalk-session.json", JSON.stringify({ title, subjectHint, diagram, opsLog, transcript }, null, 2), "application/json");
  const exportPng = async () => { const element = document.querySelector(".react-flow__renderer") as HTMLElement | null; if (!element) return; try { await downloadDataUrl("chalk-diagram.png", await toPng(element, { backgroundColor: "#111b1d", pixelRatio: 2, cacheBust: true })); } catch (caught) { console.error("PNG export failed", caught); setError("Chalk could not export the diagram image. Please try again."); } };
  const handout = async () => { setError(""); setIsExportingHandout(true); setStatus("Thinking"); try { const response = await fetch("/api/summarize", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ title, subjectHint, transcript, diagram: compactDiagram(diagram) }) }); const body: unknown = await response.json(); if (!response.ok || !body || typeof body !== "object" || !("markdown" in body) || typeof body.markdown !== "string") throw new Error(); download("chalk-handout.md", body.markdown, "text/markdown"); } catch { setError("Chalk could not create the handout yet. Please try again."); } finally { setIsExportingHandout(false); setStatus("Idle"); } };
  const restoreSession = useCallback((session: Session) => { restore({ diagram: session.diagram, opsLog: session.opsLog, transcript: session.transcript }); if (typeof session.title === "string") setTitle(session.title); if (typeof session.subjectHint === "string") setSubjectHint(session.subjectHint); }, [restore]);
  useEffect(() => { const timer = window.setTimeout(() => { if (diagram.nodes.length || transcript) localStorage.setItem("chalk-session", JSON.stringify({ title, diagram, opsLog, transcript, subjectHint })); }, 500); return () => window.clearTimeout(timer); }, [diagram, opsLog, subjectHint, title, transcript]);
  useEffect(() => { const raw = localStorage.getItem("chalk-session"); if (!raw || !window.confirm("Restore your previous Chalk session?")) return; const timer = window.setTimeout(() => { try { const session: unknown = JSON.parse(raw); if (!isSession(session)) throw new Error(); restoreSession(session); } catch { localStorage.removeItem("chalk-session"); setError("The saved Chalk session could not be restored."); } }, 0); return () => window.clearTimeout(timer); }, [restoreSession]); // Restore prompt is intentionally once per page load.
  useEffect(() => { if (!isPlaying) return; const timer = window.setTimeout(() => { if (replayIndex >= opsLog.length) setIsPlaying(false); else setReplayIndex((index) => index + 1); }, 700); return () => window.clearTimeout(timer); }, [isPlaying, opsLog.length, replayIndex]);
  const replayDiagram = useMemo(() => opsLog.slice(0, replayIndex).reduce((current, ops) => applyOps(current, ops), emptyDiagram()), [opsLog, replayIndex]); const activeDiagram = isReplay ? replayDiagram : diagram;
  const exitReplay = () => { setIsPlaying(false); setIsReplay(false); };
  const clearBoard = () => { if (!window.confirm("Clear this board and remove its saved session?")) return; localStorage.removeItem("chalk-session"); reset(); exitReplay(); };
  const loadSession = async (file: File | undefined) => { if (!file) return; try { const session: unknown = JSON.parse(await file.text()); if (!isSession(session)) throw new Error(); restoreSession(session); exitReplay(); } catch { setError("That file is not a valid Chalk session."); } };
  const loadSample = async (lines: string[], subject: string) => { reset(); exitReplay(); setTitle(subject); setSubjectHint(subject); for (const line of lines) { enqueueFinal(line, true); await new Promise((resolve) => window.setTimeout(resolve, 750)); } };
  const nodes: Node[] = useMemo(() => activeDiagram.nodes.map((node) => { const glowing = activeDiagram.highlights.includes(node.id) || pointedNodeIds.includes(node.id) || selectedNodeIds.includes(node.id); return { id: node.id, position: { x: node.x, y: node.y }, data: { label: <div className="flex flex-col gap-1"><span className="text-xs">{{ concept: "◉", actor: "♙", process: "↻", stage: "◇", data: "▦", example: "✦", note: "✎" }[node.kind]}</span><strong>{node.label}</strong>{node.note && <small>{node.note}</small>}</div> }, style: { border: `2px solid ${accent[node.kind]}`, borderRadius: 14, padding: "10px 14px", background: glowing ? `${accent[node.kind]}44` : "#1d2d2e", color: "#f5f0df", boxShadow: glowing ? `0 0 18px ${accent[node.kind]}` : "none", transition: "transform 500ms ease, box-shadow 250ms ease, background-color 250ms ease" } }; }), [activeDiagram, pointedNodeIds, selectedNodeIds]);
  const edges: Edge[] = useMemo(() => activeDiagram.edges.map((edge) => ({ ...edge, type: "smoothstep", markerEnd: edge.directed === false ? undefined : { type: MarkerType.ArrowClosed }, label: edge.label, style: { stroke: "#dce5df", strokeWidth: 1.8 }, labelStyle: { fill: "#fff8e7", fontSize: 12, fontWeight: 700 }, labelShowBg: true, labelBgStyle: { fill: "#142023", fillOpacity: 1 }, labelBgPadding: [7, 4], labelBgBorderRadius: 5 })), [activeDiagram]);
  return <main className="min-h-screen bg-[#111b1d] text-[#f5f0df]">
    <header className="flex flex-wrap items-center gap-4 border-b border-white/10 bg-[#172326] px-5 py-4"><div className="mr-4 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#e6a75b] text-xl text-[#172326]">✦</span><div><h1 className="font-semibold tracking-wide">Chalk</h1><p className="text-xs text-[#a8b3ad]">The board that draws itself</p></div></div><input aria-label="Session title" className="shell-input min-w-44 flex-1" value={title} onChange={(event) => setTitle(event.target.value)} /><input aria-label="Subject hint" className="shell-input w-52" value={subjectHint} onChange={(event) => setSubjectHint(event.target.value)} placeholder="Subject hint (optional)" /><span className="rounded-full border border-[#e6a75b]/40 bg-[#e6a75b]/10 px-3 py-1 text-sm text-[#f3c887]">{status}</span>{process.env.NODE_ENV === "development" && <button className="control-button" type="button" onClick={() => setDebugEnabled((current) => !current)}>Debug HUD</button>}</header>
    {isReplay && <div className="flex items-center gap-3 border-b border-white/10 bg-[#142023] px-5 py-2 text-sm"><span>Replay {replayIndex}/{opsLog.length}</span><input aria-label="Replay progress" className="accent-[#e6a75b]" type="range" min="0" max={opsLog.length} value={replayIndex} onChange={(event) => { setIsPlaying(false); setReplayIndex(Number(event.target.value)); }} /></div>}
    <div className="grid min-h-[calc(100vh-205px)] grid-cols-1 lg:grid-cols-[1fr_320px]"><section ref={canvasAreaRef} className="relative min-h-[520px] border-b border-white/10 lg:border-b-0 lg:border-r"><ReactFlow nodes={nodes} edges={edges} fitView fitViewOptions={{ padding: 0.22 }} onMoveStart={(event) => { if (event) manualViewportUntilRef.current = Date.now() + 4000; }} onNodeMouseEnter={(_, node) => setPointed(node.id)} onNodeMouseLeave={() => setPointed(null)} onNodeClick={() => toggleSelected()}><ViewportFitter manualUntilRef={manualViewportUntilRef} signature={activeDiagram.nodes.map((node) => `${node.id}:${node.x}:${node.y}`).join("|")} /><GestureLayer areaRef={canvasAreaRef} diagram={activeDiagram} setPointed={setPointed} toggleSelected={toggleSelected} undo={undo} setDebug={setDebug} /><Background color="#36504b" gap={24} /><Controls className="chalk-flow-controls" /></ReactFlow>{debugEnabled && <pre className="absolute left-3 top-3 z-40 max-w-72 rounded bg-black/80 p-3 text-xs text-[#f5f0df]">{JSON.stringify({ gesture: debug.gesture, pinch: debug.pinchDistance.toFixed(3), video: debug.point, screen: debug.screen, flow: debug.flow, pointed: debug.pointed, selected: selectedNodeIds, fps: debug.fps.toFixed(1) }, null, 2)}</pre>}{nodes.length === 0 && <div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="mb-3 text-5xl text-[#e6a75b]/80">✦</p><h2 className="text-xl font-medium">Your lesson will take shape here</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#a8b3ad]">Speak naturally, type an explanation below, or load the water-cycle sample.</p></div></div>}</section><aside className="flex min-h-72 flex-col bg-[#142023] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-medium">Live transcript</h2><span className="text-xs text-[#7e9089]">{status}</span></div><div ref={scrollRef} className="flex-1 overflow-auto rounded-xl border border-dashed border-white/15 p-4 text-sm leading-6"><span className="text-[#dce1dc]">{transcript || "Your final words will appear here."}</span>{interim && <span className="text-[#7e9089]"> {interim}</span>}</div></aside></div>
    <div className="border-t border-white/10 bg-[#172326] px-5 py-3"><div className="flex flex-wrap gap-2"><button className="control-button" type="button" onClick={isListening ? stopListening : startListening} disabled={isReplay}>{isListening ? "Stop listening" : "Start listening"}</button><button className="control-button" type="button" onClick={undo} disabled={!undoStack.length || isReplay}>Undo</button><button className="control-button" type="button" onClick={() => window.dispatchEvent(new Event("chalk:fit-view"))}>Fit view</button><button className="control-button" type="button" onClick={() => void exportPng()}>Export PNG</button><button className="control-button" type="button" onClick={exportJson}>Save JSON</button><button className="control-button" type="button" onClick={() => fileInputRef.current?.click()}>Load JSON</button><input ref={fileInputRef} className="hidden" type="file" accept="application/json" onChange={(event) => { void loadSession(event.target.files?.[0]); event.currentTarget.value = ""; }} /><button className="control-button" type="button" onClick={() => void handout()} disabled={!transcript || isExportingHandout}>{isExportingHandout ? "Preparing handout…" : "Download handout (.md)"}</button>{!isReplay ? <button className="control-button" type="button" onClick={() => { setReplayIndex(0); setIsPlaying(false); setIsReplay(true); }} disabled={!opsLog.length}>Replay</button> : <><button className="control-button" type="button" onClick={() => setIsPlaying((playing) => !playing)}>{isPlaying ? "Pause replay" : "Play replay"}</button><button className="control-button" type="button" onClick={() => setReplayIndex((index) => Math.min(opsLog.length, index + 1))} disabled={replayIndex >= opsLog.length}>Step {replayIndex}/{opsLog.length}</button><button className="control-button" type="button" onClick={exitReplay}>Exit replay</button></>}<button className="control-button" type="button" onClick={() => void loadSample(WATER_CYCLE, "Water cycle")}>Load water-cycle sample</button><button className="control-button" type="button" onClick={() => void loadSample(WORLD_WAR_I, "World War I")}>Load WWI sample</button><button className="control-button" type="button" onClick={clearBoard}>Clear board</button></div><div className="mt-3 flex gap-2"><textarea aria-label="Typed input" className="shell-input min-h-20 flex-1" value={text} disabled={isReplay} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") { event.preventDefault(); submitTyped(); } }} placeholder="Typed input stays available — Ctrl/Cmd + Enter to draw…" /><button className="rounded-lg bg-[#e6a75b] px-4 py-2 font-medium text-[#172326]" type="button" onClick={submitTyped} disabled={isReplay}>Draw it</button></div>{error && <p role="alert" className="mt-2 text-sm text-[#e99a99]">{error}</p>}</div>
  </main>;
}
