"use client";

import { useCallback, useMemo, useState } from "react";
import { Background, Controls, MarkerType, ReactFlow, type Edge, type Node } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { create } from "zustand";
import { applyOps, compactDiagram, emptyDiagram, publicDiagramOpsSchema, type Diagram, type DiagramOp } from "@/lib/diagram";

type BoardStore = { diagram: Diagram; undoStack: Diagram[]; transcript: string; status: "Idle" | "Thinking" | "Drawing"; apply: (ops: DiagramOp[], delta: string) => void; undo: () => void; reset: () => void };
const useBoard = create<BoardStore>((set) => ({ diagram: emptyDiagram(), undoStack: [], transcript: "", status: "Idle", apply: (ops, delta) => set((state) => ({ undoStack: [...state.undoStack, structuredClone(state.diagram)], diagram: applyOps(state.diagram, ops), transcript: `${state.transcript} ${delta}`.trim(), status: "Drawing" })), undo: () => set((state) => { const previous = state.undoStack.at(-1); return previous ? { diagram: previous, undoStack: state.undoStack.slice(0, -1), status: "Idle" } : state; }), reset: () => set({ diagram: emptyDiagram(), undoStack: [], transcript: "", status: "Idle" }) }));

const accent: Record<string, string> = { concept: "#e6a75b", actor: "#7ab8c4", process: "#b394d8", stage: "#77b78c", data: "#d7828b", example: "#d8b55e", note: "#c6c5bd" };
const WATER_CYCLE = ["The sun heats the ocean, causing evaporation.", "Water vapor rises and cools into clouds through condensation.", "Then precipitation falls from clouds back to the ocean, and the cycle repeats."];

export function ChalkBoard() {
  const { diagram, undoStack, transcript, status, apply, undo, reset } = useBoard();
  const [text, setText] = useState(""); const [subjectHint, setSubjectHint] = useState("Water cycle"); const [error, setError] = useState("");
  const nodes: Node[] = useMemo(() => diagram.nodes.map((node) => ({ id: node.id, position: { x: node.x, y: node.y }, data: { label: <div><strong>{node.label}</strong>{node.note && <small>{node.note}</small>}</div> }, style: { border: `2px solid ${accent[node.kind]}`, borderRadius: 14, padding: "10px 14px", background: diagram.highlights.includes(node.id) ? `${accent[node.kind]}44` : "#1d2d2e", color: "#f5f0df", boxShadow: diagram.highlights.includes(node.id) ? `0 0 18px ${accent[node.kind]}` : "none" } })), [diagram]);
  const edges: Edge[] = useMemo(() => diagram.edges.map((edge) => ({ ...edge, markerEnd: edge.directed === false ? undefined : { type: MarkerType.ArrowClosed }, label: edge.label, style: { stroke: "#a8b3ad" }, labelStyle: { fill: "#d9ded7", fontSize: 11 } })), [diagram]);
  const submit = useCallback(async (delta = text) => {
    const clean = delta.trim(); if (!clean) return; setError(""); useBoard.setState({ status: "Thinking" });
    try { const response = await fetch("/api/interpret", { method: "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcriptDelta: clean, recentTranscript: `${transcript} ${clean}`.slice(-1500), diagram: compactDiagram(useBoard.getState().diagram), pointerContext: { pointedNodeIds: [], selectedNodeIds: [] }, subjectHint }) }); const body: unknown = await response.json(); const parsed = publicDiagramOpsSchema.safeParse(body); if (!response.ok || !parsed.success) throw new Error("The response was not usable."); apply(parsed.data.ops, clean); setText(""); window.setTimeout(() => useBoard.setState({ status: "Idle" }), 500); } catch (caught) { useBoard.setState({ status: "Idle" }); setError(caught instanceof Error ? caught.message : "Try again."); }
  }, [apply, subjectHint, text, transcript]);
  const loadWaterCycle = async () => { reset(); for (const line of WATER_CYCLE) await submit(line); };
  return <main className="min-h-screen bg-[#111b1d] text-[#f5f0df]">
    <header className="flex flex-wrap items-center gap-4 border-b border-white/10 bg-[#172326] px-5 py-4"><div className="mr-4 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#e6a75b] text-xl text-[#172326]">✦</span><div><h1 className="font-semibold tracking-wide">Chalk</h1><p className="text-xs text-[#a8b3ad]">The board that draws itself</p></div></div><input aria-label="Session title" className="shell-input min-w-44 flex-1" defaultValue="Untitled lesson" /><input aria-label="Subject hint" className="shell-input w-52" value={subjectHint} onChange={(event) => setSubjectHint(event.target.value)} placeholder="Subject hint (optional)" /><span className="rounded-full border border-[#e6a75b]/40 bg-[#e6a75b]/10 px-3 py-1 text-sm text-[#f3c887]">{status}</span></header>
    <div className="grid min-h-[calc(100vh-205px)] grid-cols-1 lg:grid-cols-[1fr_320px]"><section className="relative min-h-[520px] border-b border-white/10 lg:border-b-0 lg:border-r"><ReactFlow nodes={nodes} edges={edges} fitView><Background color="#36504b" gap={24} /><Controls /></ReactFlow>{nodes.length === 0 && <div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="mb-3 text-5xl text-[#e6a75b]/80">✦</p><h2 className="text-xl font-medium">Your lesson will take shape here</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#a8b3ad]">Type an explanation below or load the water-cycle sample.</p></div></div>}</section><aside className="flex min-h-72 flex-col bg-[#142023] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-medium">Live transcript</h2><span className="text-xs text-[#7e9089]">{transcript ? "Updated" : "Waiting"}</span></div><div className="flex-1 overflow-auto rounded-xl border border-dashed border-white/15 p-4 text-sm leading-6 text-[#cbd2cc]">{transcript || "Your final words will appear here."}</div></aside></div>
    <div className="border-t border-white/10 bg-[#172326] px-5 py-3"><div className="flex flex-wrap gap-2"><button className="control-button" type="button" onClick={undo} disabled={!undoStack.length}>Undo</button><button className="control-button" type="button" onClick={loadWaterCycle}>Load water-cycle sample</button><button className="control-button" type="button" onClick={reset}>Clear board</button></div><div className="mt-3 flex gap-2"><textarea aria-label="Typed input" className="shell-input min-h-20 flex-1" value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") { event.preventDefault(); void submit(); } }} placeholder="Type one idea at a time, then Ctrl/Cmd + Enter…" /><button className="rounded-lg bg-[#e6a75b] px-4 py-2 font-medium text-[#172326]" type="button" onClick={() => void submit()}>Draw it</button></div>{error && <p role="alert" className="mt-2 text-sm text-[#e99a99]">{error}</p>}</div>
  </main>;
}
