"use client";

import { useCallback, useEffect, useMemo, useRef, useState } from "react";
import { Background, Controls, MarkerType, ReactFlow, useReactFlow, type Edge, type Node } from "@xyflow/react";
import "@xyflow/react/dist/style.css";
import { create } from "zustand";
import { applyOps, compactDiagram, emptyDiagram, publicDiagramOpsSchema, type Diagram, type DiagramOp } from "@/lib/diagram";
import { layoutDiagram } from "@/lib/layout";
import { WebSpeechTranscriptSource, type TranscriptHandlers, type TranscriptSource } from "@/lib/transcript-source";

type BoardStatus = "Idle" | "Listening" | "Thinking" | "Drawing";
type BoardStore = { diagram: Diagram; undoStack: Diagram[]; transcript: string; interim: string; status: BoardStatus; apply: (ops: DiagramOp[]) => Diagram; setPositions: (nodes: Diagram["nodes"]) => void; addFinal: (text: string) => void; setInterim: (text: string) => void; setStatus: (status: BoardStatus) => void; undo: () => void; reset: () => void };
const useBoard = create<BoardStore>((set, get) => ({ diagram: emptyDiagram(), undoStack: [], transcript: "", interim: "", status: "Idle", apply: (ops) => { const next = applyOps(get().diagram, ops); set((state) => ({ undoStack: [...state.undoStack, structuredClone(state.diagram)], diagram: next, status: "Drawing" })); return next; }, setPositions: (nodes) => set((state) => ({ diagram: { ...state.diagram, nodes } })), addFinal: (text) => set((state) => ({ transcript: `${state.transcript} ${text}`.trim(), interim: "" })), setInterim: (interim) => set({ interim }), setStatus: (status) => set({ status }), undo: () => set((state) => { const previous = state.undoStack.at(-1); return previous ? { diagram: previous, undoStack: state.undoStack.slice(0, -1), status: "Idle" } : state; }), reset: () => set({ diagram: emptyDiagram(), undoStack: [], transcript: "", interim: "", status: "Idle" }) }));

const accent: Record<string, string> = { concept: "#e6a75b", actor: "#7ab8c4", process: "#b394d8", stage: "#77b78c", data: "#d7828b", example: "#d8b55e", note: "#c6c5bd" };
const WATER_CYCLE = ["The sun heats the ocean, causing evaporation.", "Water vapor rises and cools into clouds through condensation.", "Then precipitation falls from clouds back to the ocean, and the cycle repeats."];
const WORLD_WAR_I = ["World War One began in 1914 after the assassination of Archduke Franz Ferdinand.", "The alliance system drew Germany, Austria-Hungary, France, Britain, and Russia into the conflict.", "The war ended in 1918, followed by the Treaty of Versailles."];

function ViewportFitter({ signature }: { signature: string }) {
  const { fitView } = useReactFlow();
  useEffect(() => { const timer = window.setTimeout(() => { void fitView({ padding: 0.22, duration: 500 }); }, 0); return () => window.clearTimeout(timer); }, [fitView, signature]);
  return null;
}

export function ChalkBoard() {
  const { diagram, undoStack, transcript, interim, status, apply, setPositions, addFinal, setInterim, setStatus, undo, reset } = useBoard();
  const [text, setText] = useState(""); const [subjectHint, setSubjectHint] = useState("Water cycle"); const [error, setError] = useState(""); const [isListening, setIsListening] = useState(false);
  const sourceRef = useRef<TranscriptSource | null>(null); const listeningRef = useRef(false); const requestRef = useRef<AbortController | null>(null); const queuedRef = useRef(""); const transcriptRef = useRef(""); const subjectRef = useRef(subjectHint); const scrollRef = useRef<HTMLDivElement>(null); const sendRef = useRef<() => void>(() => undefined);
  useEffect(() => { transcriptRef.current = transcript; }, [transcript]); useEffect(() => { subjectRef.current = subjectHint; }, [subjectHint]); useEffect(() => { scrollRef.current?.scrollTo({ top: scrollRef.current.scrollHeight }); }, [transcript, interim]);
  const finishDrawing = useCallback(() => window.setTimeout(() => setStatus(listeningRef.current ? "Listening" : "Idle"), 450), [setStatus]);
  const send = useCallback(async () => {
    const delta = queuedRef.current.trim(); if (!delta || requestRef.current) return; queuedRef.current = ""; const controller = new AbortController(); requestRef.current = controller; setStatus("Thinking");
    try { const response = await fetch("/api/interpret", { method: "POST", signal: controller.signal, headers: { "Content-Type": "application/json" }, body: JSON.stringify({ transcriptDelta: delta, recentTranscript: `${transcriptRef.current} ${delta}`.trim().slice(-1500), diagram: compactDiagram(useBoard.getState().diagram), pointerContext: { pointedNodeIds: [], selectedNodeIds: [] }, subjectHint: subjectRef.current || undefined }) }); const parsed = publicDiagramOpsSchema.safeParse(await response.json()); if (!response.ok || !parsed.success) throw new Error("Chalk could not interpret that yet. Please try again."); const nextDiagram = apply(parsed.data.ops); const positionedNodes = await layoutDiagram(nextDiagram); setPositions(positionedNodes); finishDrawing(); } catch (caught) { if (!(caught instanceof DOMException && caught.name === "AbortError")) { setError(caught instanceof Error ? caught.message : "Try again."); setStatus(listeningRef.current ? "Listening" : "Idle"); } } finally { requestRef.current = null; if (queuedRef.current.trim() && !controller.signal.aborted) sendRef.current(); }
  }, [apply, finishDrawing, setPositions, setStatus]);
  useEffect(() => { sendRef.current = () => { void send(); }; }, [send]);
  const enqueueFinal = useCallback((value: string, sendImmediately: boolean) => { const clean = value.trim(); if (!clean) return; addFinal(clean); queuedRef.current = `${queuedRef.current} ${clean}`.trim(); if (sendImmediately) void send(); }, [addFinal, send]);
  useEffect(() => { const interval = window.setInterval(() => { if (queuedRef.current.trim().length >= 80 && !requestRef.current) void send(); }, 4000); return () => window.clearInterval(interval); }, [send]);
  const stopListening = useCallback(() => { listeningRef.current = false; setIsListening(false); sourceRef.current?.stop(); sourceRef.current = null; queuedRef.current = ""; requestRef.current?.abort(); requestRef.current = null; setInterim(""); setStatus("Idle"); }, [setInterim, setStatus]);
  const startListening = useCallback(() => { setError(""); const source = new WebSpeechTranscriptSource(); if (!source.supported) { setError("Speech recognition needs Chrome desktop. Typed input is ready below."); setStatus("Idle"); return; } sourceRef.current = source; listeningRef.current = true; setIsListening(true); setStatus("Listening"); const handlers: TranscriptHandlers = { onFinal: (finalText) => enqueueFinal(finalText, true), onInterim: setInterim, onError: (message) => { setError(message); stopListening(); }, onEnd: () => { if (listeningRef.current) window.setTimeout(() => { if (listeningRef.current) source.start(handlers); }, 150); } }; source.start(handlers); }, [enqueueFinal, setInterim, setStatus, stopListening]);
  useEffect(() => () => stopListening(), [stopListening]);
  const submitTyped = useCallback(() => { enqueueFinal(text, true); setText(""); }, [enqueueFinal, text]);
  const loadSample = async (lines: string[], subject: string) => { reset(); setSubjectHint(subject); for (const line of lines) { enqueueFinal(line, true); await new Promise((resolve) => window.setTimeout(resolve, 750)); } };
  const nodes: Node[] = useMemo(() => diagram.nodes.map((node) => ({ id: node.id, position: { x: node.x, y: node.y }, data: { label: <div className="flex flex-col gap-1"><span className="text-xs">{{ concept: "◉", actor: "♙", process: "↻", stage: "◆", data: "▦", example: "✦", note: "✎" }[node.kind]}</span><strong>{node.label}</strong>{node.note && <small>{node.note}</small>}</div> }, style: { border: `2px solid ${accent[node.kind]}`, borderRadius: 14, padding: "10px 14px", background: diagram.highlights.includes(node.id) ? `${accent[node.kind]}44` : "#1d2d2e", color: "#f5f0df", boxShadow: diagram.highlights.includes(node.id) ? `0 0 18px ${accent[node.kind]}` : "none", transition: "transform 500ms ease, box-shadow 250ms ease, background-color 250ms ease" } })), [diagram]);
  const edges: Edge[] = useMemo(() => diagram.edges.map((edge) => ({ ...edge, markerEnd: edge.directed === false ? undefined : { type: MarkerType.ArrowClosed }, label: edge.label, style: { stroke: "#dce5df", strokeWidth: 1.8 }, labelStyle: { fill: "#fff8e7", fontSize: 12, fontWeight: 700 }, labelBgStyle: { fill: "#142023", fillOpacity: 0.96 }, labelBgPadding: [5, 3], labelBgBorderRadius: 4 })), [diagram]);
  return <main className="min-h-screen bg-[#111b1d] text-[#f5f0df]">
    <header className="flex flex-wrap items-center gap-4 border-b border-white/10 bg-[#172326] px-5 py-4"><div className="mr-4 flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-[#e6a75b] text-xl text-[#172326]">✦</span><div><h1 className="font-semibold tracking-wide">Chalk</h1><p className="text-xs text-[#a8b3ad]">The board that draws itself</p></div></div><input aria-label="Session title" className="shell-input min-w-44 flex-1" defaultValue="Untitled lesson" /><input aria-label="Subject hint" className="shell-input w-52" value={subjectHint} onChange={(event) => setSubjectHint(event.target.value)} placeholder="Subject hint (optional)" /><span className="rounded-full border border-[#e6a75b]/40 bg-[#e6a75b]/10 px-3 py-1 text-sm text-[#f3c887]">{status}</span></header>
    <div className="grid min-h-[calc(100vh-205px)] grid-cols-1 lg:grid-cols-[1fr_320px]"><section className="relative min-h-[520px] border-b border-white/10 lg:border-b-0 lg:border-r"><ReactFlow nodes={nodes} edges={edges} fitView fitViewOptions={{ padding: 0.22 }}><ViewportFitter signature={diagram.nodes.map((node) => `${node.id}:${node.x}:${node.y}`).join("|")} /><Background color="#36504b" gap={24} /><Controls /></ReactFlow>{nodes.length === 0 && <div className="pointer-events-none absolute inset-0 grid place-items-center text-center"><div><p className="mb-3 text-5xl text-[#e6a75b]/80">✦</p><h2 className="text-xl font-medium">Your lesson will take shape here</h2><p className="mt-2 max-w-sm text-sm leading-6 text-[#a8b3ad]">Speak naturally, type an explanation below, or load the water-cycle sample.</p></div></div>}</section><aside className="flex min-h-72 flex-col bg-[#142023] p-5"><div className="mb-4 flex items-center justify-between"><h2 className="font-medium">Live transcript</h2><span className="text-xs text-[#7e9089]">{status}</span></div><div ref={scrollRef} className="flex-1 overflow-auto rounded-xl border border-dashed border-white/15 p-4 text-sm leading-6"><span className="text-[#dce1dc]">{transcript || "Your final words will appear here."}</span>{interim && <span className="text-[#7e9089]"> {interim}</span>}</div></aside></div>
    <div className="border-t border-white/10 bg-[#172326] px-5 py-3"><div className="flex flex-wrap gap-2"><button className="control-button" type="button" onClick={isListening ? stopListening : startListening}>{isListening ? "Stop listening" : "Start listening"}</button><button className="control-button" type="button" onClick={undo} disabled={!undoStack.length}>Undo</button><button className="control-button" type="button" onClick={() => void loadSample(WATER_CYCLE, "Water cycle")}>Load water-cycle sample</button><button className="control-button" type="button" onClick={() => void loadSample(WORLD_WAR_I, "World War I")}>Load WWI sample</button><button className="control-button" type="button" onClick={reset}>Clear board</button></div><div className="mt-3 flex gap-2"><textarea aria-label="Typed input" className="shell-input min-h-20 flex-1" value={text} onChange={(event) => setText(event.target.value)} onKeyDown={(event) => { if ((event.ctrlKey || event.metaKey) && event.key === "Enter") { event.preventDefault(); submitTyped(); } }} placeholder="Typed input stays available — Ctrl/Cmd + Enter to draw…" /><button className="rounded-lg bg-[#e6a75b] px-4 py-2 font-medium text-[#172326]" type="button" onClick={submitTyped}>Draw it</button></div>{error && <p role="alert" className="mt-2 text-sm text-[#e99a99]">{error}</p>}</div>
  </main>;
}
