// Generated by scripts/generate-media-manifest.mjs. Do not edit by hand.
export const availableRecordingFiles: readonly string[] = [];
export const availableAudioFiles: readonly string[] = [];
export const mediaDurationsSec: Readonly<Record<string, number>> = {};
