// Generated by scripts/generate-media-manifest.mjs. Do not edit by hand.
export const availableRecordingFiles: readonly string[] = ["handout.mp4","hook.mp4","segment-a-voice-build.mp4","segment-b-gestures.mp4","segment-c-artifacts.mp4"];
export const availableAudioFiles: readonly string[] = [];
export const mediaDurationsSec: Readonly<Record<string, number>> = {"recordings/handout.mp4":7.21,"recordings/hook.mp4":8.01,"recordings/segment-a-voice-build.mp4":57.6,"recordings/segment-b-gestures.mp4":22.42,"recordings/segment-c-artifacts.mp4":22.89};
